FROM php:8.2-cli

RUN apt-get update \
 && apt-get install -y git unzip openssh-client netcat-openbsd libssh2-1-dev \
 && pecl install ssh2 \
 && docker-php-ext-enable ssh2 \
 && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app